const now = new Date().toISOString();

const themeSeeds = [
  {
    id: 'vibe-coding',
    code: '01',
    name: 'Vibe Coding教程',
    subtitle: 'Vibe Coding入门',
    coverImage: '/themes/vibe-cover.jpg',
    bannerImage: '/themes/vibe-banner.jpg',
    gallery: [],
    introVideo: '',
    layout: {
      heroStyle: 'overlay',
      cardColumns: 3,
      sectionOrder: ['banner', 'gallery', 'articles'],
    },
    sortOrder: 1,
    isActive: true,
    createdAt: now,
  },
  {
    id: 'claude-dev',
    code: '02',
    name: 'Claude AI开发教程',
    subtitle: 'Claude开发实战',
    coverImage: '/themes/claude-cover.jpg',
    bannerImage: '/themes/claude-banner.jpg',
    gallery: [],
    introVideo: '',
    layout: {
      heroStyle: 'split',
      cardColumns: 3,
      sectionOrder: ['banner', 'articles'],
    },
    sortOrder: 2,
    isActive: true,
    createdAt: now,
  },
  {
    id: 'openclaw-tools',
    code: '03',
    name: 'OpenClaw工具教程',
    subtitle: 'OpenClaw工具链',
    coverImage: '/themes/openclaw-cover.jpg',
    bannerImage: '/themes/openclaw-banner.jpg',
    gallery: [],
    introVideo: '',
    layout: {
      heroStyle: 'full',
      cardColumns: 3,
      sectionOrder: ['banner', 'articles'],
    },
    sortOrder: 3,
    isActive: true,
    createdAt: now,
  },
  {
    id: 'pm-ai-tools',
    code: '04',
    name: '产品经理AI工具教程',
    subtitle: '智能工作流指南',
    coverImage: '/themes/pm-cover.jpg',
    bannerImage: '/themes/pm-banner.jpg',
    gallery: [],
    introVideo: '',
    layout: {
      heroStyle: 'overlay',
      cardColumns: 2,
      sectionOrder: ['banner', 'articles'],
    },
    sortOrder: 4,
    isActive: true,
    createdAt: now,
  },
  {
    id: 'obsidian-notes',
    code: '05',
    name: 'Obsidian笔记教程',
    subtitle: 'Obsidian+AI笔记',
    coverImage: '/themes/obsidian-cover.jpg',
    bannerImage: '/themes/obsidian-banner.jpg',
    gallery: [],
    introVideo: '',
    layout: {
      heroStyle: 'split',
      cardColumns: 2,
      sectionOrder: ['banner', 'gallery', 'articles'],
    },
    sortOrder: 5,
    isActive: true,
    createdAt: now,
  },
  {
    id: 'coding-fundamentals',
    code: '06',
    name: '编程基础精讲',
    subtitle: '—',
    coverImage: '/themes/fundamentals-cover.jpg',
    bannerImage: '/themes/fundamentals-banner.jpg',
    gallery: [],
    introVideo: '',
    layout: {
      heroStyle: 'overlay',
      cardColumns: 3,
      sectionOrder: ['banner', 'articles'],
    },
    sortOrder: 6,
    isActive: true,
    createdAt: now,
  },
];

module.exports = { themeSeeds };
